name: Build Lineage Kernel with KernelSU 0.9.5 (Legacy version)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'LineageOS Version'
        required: true
        default: '18.1'

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: Remove unused packages
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: false
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
      - name: Configure Git
        run: |
          git config --global user.name "meokira"
          git config --global user.email "meo-arkia@email.ncu.edu.cn"
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          ref: master
          path: repo
      - name: Checkout kernel code
        uses: actions/checkout@v4
        with:
          repository: meokira/testbuild
          ref: lineage-${{ github.event.inputs.version }}
          path: testbuild
      - name: Checkout AnyKernel3 code
        uses: actions/checkout@v4
        with:
          repository: osm0sis/AnyKernel3
          ref: master
          path: AnyKernel3
      - name: Configure AnyKernel3
        run: |
          cd AnyKernel3
          rm anykernel.sh
          cp -f ../repo/anykernel.sh .
      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 2G
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi
          sudo apt-get install binutils make python3 libssl-dev build-essential bc bison flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs
      - name: Check KernelSU code
        run: |
          cd testbuild
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5
      - name: Get version and commit
        run: |
          cd testbuild/KernelSU
          VERSION=$(($(git rev-list --count HEAD) + 10200))
          echo "KSU_VERSION=$VERSION" >> $GITHUB_ENV
          echo $VERSION
      - name: Enable KPROBES
        run: |
          cd testbuild
          CONFIG_FILE=./arch/arm64/configs/lineageos_kuntao_defconfig
          echo "CONFIG_KPROBES=y" >> "$CONFIG_FILE"
          echo "CONFIG_HAVE_KPROBES=y" >> "$CONFIG_FILE"
          echo "CONFIG_KPROBE_EVENTS=y" >> "$CONFIG_FILE"
      - name: Download clang
        run: |
          wget https://github.com/Snownamida/Polaris_Kernel/raw/refs/heads/master/Cross_Compile/aarch64-linux-android-4.9-d7d824eaa0690179c4b504209dbb017dfc730cf3.tar.gz
          tar xf aarch64-linux-android-4.9-d7d824eaa0690179c4b504209dbb017dfc730cf3.tar.gz
      - name: Build Kernel With KernelSU
        run: |
          export PATH=$(pwd)/aarch64-linux-android-4.9-d7d824eaa0690179c4b504209dbb017dfc730cf3/bin/:$PATH
          cd testbuild
          make O=out $KERNEL_DEFCONFIG
          make -j$(nproc --all) O=out ARCH=arm64 SUBARCH=arm64 CC="ccache gcc" CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          cp out/arch/arm64/boot/Image.gz-dtb ../AnyKernel3
        env:
          KERNEL_DEFCONFIG: "lineageos_kuntao_defconfig"
          ARCH: arm64
          SUBARCH: arm64
      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3_Lineage-${{ github.event.inputs.version }}_${{ env.KSU_VERSION }}
          path: "AnyKernel3/*"
  
